#!/bin/bash -l
#Parameters of the Jobs :

#$-P tcwlab
#$-j y
#$-l h_rt=24:00:00
#$-o  logs/01-split_per_cell_type.py.log
#$-pe omp 4


#Micromamba environment activation:

micromamba activate singlecell


#keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
if [[ -n "${SGE_TASK_ID}" && $SGE_TASK_ID != "undefined" ]]; then
    echo "Task index number : $SGE_TASK_ID"
fi
if [[ -n "${SGE_TASK_LAST}" && $SGE_TASK_LAST != "undefined" ]]; then
    echo "Total task number : $SGE_TASK_LAST"
fi
echo "=========================================================="

python scripts/01-split_per_cell_type.py >> logs/01-split_per_cell_type.py.log



echo "=========================================================="
echo "Finished Analysis for $PROJ_NAME on : $(date)"
echo "=========================================================="

