#!/bin/bash -l

# this file serving as template for creating customized qsub file, 
# the file name shall be changed properly after customized for job.
# run 'qsub [-N jobname] myjobname.qsub projectname'
#
# All lines starting with "#" are comments
# All lines starting with "#$" are SGE qsub commands
#
# Set SCC project
#$ -P tcwlab

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=12:00:00

# Combine output and error files into a single file
#$ -j y

#  Name the log directory where to redirect standard output and error
#$ -o logs/01.log # make sure qlog/ exists and is in the working directory, otherwise give the full path.


#  request enough memory:
#$ -l mem_per_core=8G

# Specify computing resources
# can be omp, 
#$ -pe omp 16


# Now let's keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
if [[ -n "${SGE_TASK_ID}" && $SGE_TASK_ID != "undefined" ]]; then
    echo "Task index number : $SGE_TASK_ID"
fi
if [[ -n "${SGE_TASK_LAST}" && $SGE_TASK_LAST != "undefined" ]]; then
    echo "Total task number : $SGE_TASK_LAST"
fi
echo "=========================================================="


# Load any modules you might want to use.
module load R/4.2.1
#source $HOME/.bashrc

#PATH={COMMON_SCRIPT_DIR}:$PATH

Rscript scripts/01-get_seaad_data.R > logs/01.Rlog



echo "=========================================================="
echo "Finished Analysis for $PROJ_NAME on : $(date)"
echo "=========================================================="

