#!/bin/bash -l
#Parameters of the Jobs :

#$-P  tcwlab-adsp
#$-j y
#$-l h_rt=24:00:00
#$-o  ./logs/05B-kinship.log
#$-pe omp 28


# loading of bashrc profile:
 source $HOME/.bashrc

#Micromamba environment activation:

micromamba activate pisces-rabbit

# singularity specifics configuration: 
export SINGULARITY_BIND="$TMP,/restricted/projectnb/tcwlab-adsp/,/projectnb/tcwlab-adsp/,/projectnb/tcwlab/"
touch .Rprofile


#keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
if [[ -n "${SGE_TASK_ID}" && $SGE_TASK_ID != "undefined" ]]; then
    echo "Task index number : $SGE_TASK_ID"
fi
if [[ -n "${SGE_TASK_LAST}" && $SGE_TASK_LAST != "undefined" ]]; then
    echo "Total task number : $SGE_TASK_LAST"
fi
echo "=========================================================="

echo "----- Processing of kinship -----"
sos run /projectnb/tcwlab-adsp/member/adpelle1/projects/fungen-xqtl/xqtl-pipeline/pipeline//GWAS_QC.ipynb king --cwd outputs/05-ROSMAP_MIT_WGS//kinship --genoFile outputs/05-ROSMAP_MIT_WGS//ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc_match_snRNA --name ROSMAP-snRNA --no-maximize-unrelated --mem 100G -s force --container oras://ghcr.io/cumc/bioinfo_apptainer:latest

# Singularity specifics clean up: 
rm .Rprofile



echo "=========================================================="
echo "Finished Analysis for job $JOB_ID on : $(date)"
echo "=========================================================="

