#!/bin/bash -l
#Parameters of the Jobs :

#$-P  tcwlab-adsp
#$-j y
#$-l h_rt=24:00:00
#$-o  ./logs/05D-proj_related.log
#$-pe omp 16


#Micromamba environment activation:

micromamba activate pisces-rabbit

# singularity specifics configuration: 
export SINGULARITY_BIND="$TMP,/restricted/projectnb/tcwlab-adsp/,/projectnb/tcwlab-adsp/,/projectnb/tcwlab/"
touch .Rprofile


#keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
if [[ -n "${SGE_TASK_ID}" && $SGE_TASK_ID != "undefined" ]]; then
    echo "Task index number : $SGE_TASK_ID"
fi
if [[ -n "${SGE_TASK_LAST}" && $SGE_TASK_LAST != "undefined" ]]; then
    echo "Total task number : $SGE_TASK_LAST"
fi
echo "=========================================================="

sos run /projectnb/tcwlab-adsp/member/adpelle1/projects/fungen-xqtl/xqtl-pipeline/pipeline//PCA.ipynb project_samples --cwd outputs/05-ROSMAP_MIT_WGS/ --genoFile  --pca-model  --maha-k 2 --container oras://ghcr.io/cumc/flashpcar_apptainer:latest

# Singularity specifics clean up: 
rm .Rprofile



echo "=========================================================="
echo "Finished Analysis for job $JOB_ID on : $(date)"
echo "=========================================================="

